export const SET_LOGIN_USER_INFO = "SET_LOGIN_USER_INFO";

//简历信息
export const SET_RESUME_DATA = "SET_RESUME_DATA"

export const SET_COMPANY_DATA = "SET_COMPANY_DATA"

export const SET_INDEX_MODULE = 'SET_INDEX_MODULE';

export const SET_SHOW_COMPANY_DATA = 'SET_SHOW_COMPANY_DATA'

export const SET_RESUME_SIGN = 'SET_RESUME_SIGN'

export const SET_CLICK_COMMENT_INDEX = 'SET_CLICK_COMMENT_INDEX'

export const SET_CLICK_COMMENT_DETAIL_INDEX = 'SET_CLICK_COMMENT_DETAIL_INDEX'

export const SET_REPLY_DATA = 'SET_REPLY_DATA';
